define(function(require,exports,module){
	module.exports.onEnter=function()
	{
		$.mobile.activePage.css("height","100%")
	}
	module.exports.make=function(event)
	{
		_loadApp("make_cocktails");
	}
	module.exports.fav=function(event)
	{
		_loadApp("fav");
	}
	module.exports.mix_up=function(event)
	{
		_loadApp("mix-up");
	}
})