define(function(require,exports,module){
	module.exports.onEnter=function()
	{
		$.mobile.activePage.css("height","110%")
	}
	module.exports.make=function(event)
	{
		_loadApp("make_cocktails");
	}
})