define(function(require,exports,module){
	module.exports.onEnter=function()
	{
		$.mobile.activePage.css("height","100%")
		initializeDB();
	}
	module.exports.make=function(event)
	{
		_loadApp("make_cocktails");
	}
	module.exports.fav=function(event)
	{
		_loadApp("fav");
	}
	module.exports.mix_up=function(event)
	{
		_loadApp("mix-up");
	}
	module.exports.config=function(event)
	{
		_loadApp("config");
	}
	initializeDB=function(){
		var dbs=require("js/services/databaseService");
		dbs.createDatabase(app.dbConfig.migration_version,function(){
			console.log("database initialized");
		});
	}
})